_wandb:
    value:
        cli_version: 0.21.1
        e:
            2he2aopkyfjtj46qqzjf9evkszmltd99:
                args:
                    - --config
                    - allweather.yml
                    - --resume
                    - /content/drive/MyDrive/miniproject1/WeatherDiff64.pth.tar
                    - --test_set
                    - raindrop
                    - --sampling_timesteps
                    - "10"
                    - --grid_r
                    - "4"
                codePath: eval_diffusion.py
                codePathLocal: eval_diffusion.py
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "41927233536"
                email: ity0526@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: ed91bd190f8a452f5b97b98e64f8554e7182276f
                    remote: https://github.com/e-jungs2/Weather-Diffusion.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-bca5b83a-a157-fd8c-0902-0149e456e274
                host: f78d18218351
                memory:
                    total: "13608370176"
                os: Linux-6.1.123+-x86_64-with-glibc2.35
                program: /content/Weather-Diffusion/eval_diffusion.py
                python: CPython 3.12.11
                root: /content/Weather-Diffusion
                startedAt: "2025-08-27T02:26:25.724306Z"
                writerId: 2he2aopkyfjtj46qqzjf9evkszmltd99
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
                - 51
                - 105
            "2":
                - 1
                - 41
                - 51
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
grid_r:
    value: 4
sampling_steps:
    value: 10
test_set:
    value: raindrop
